// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperVideos.SharedKernel.Contexts;

namespace SuperVideos.SharedKernel.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("SuperVideos.Domain.Entities.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Available")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContenType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Delete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Sleeve")
                        .HasColumnType("BLOB");

                    b.Property<string>("Synopsis")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("SuperVideos.Domain.Entities.Movie", b =>
                {
                    b.OwnsOne("SuperVideos.Domain.Entities.ValueObject.MovieDetail", "MovieDetail", b1 =>
                        {
                            b1.Property<Guid>("MovieId")
                                .HasColumnType("TEXT");

                            b1.Property<long>("BarCode")
                                .HasColumnType("INTEGER")
                                .HasColumnName("BarCode");

                            b1.Property<string>("Code")
                                .HasColumnType("TEXT")
                                .HasColumnName("Code");

                            b1.Property<int>("Duration")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Duration");

                            b1.Property<long>("Isbn")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Isbn");

                            b1.HasKey("MovieId");

                            b1.HasIndex("Code")
                                .IsUnique();

                            b1.ToTable("Movies");

                            b1.WithOwner()
                                .HasForeignKey("MovieId");
                        });

                    b.Navigation("MovieDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
